name: anesi_media_pro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  acr_cloud_sdk: ^2.0.2
  animations: ^2.0.7
  assets_audio_player: ^3.0.6
  audio_session: ^0.1.13
  audio_video_progress_bar: ^1.0.1
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_slidable: ^3.0.0
  hooks_riverpod: ^2.3.6
  on_audio_query: ^2.8.1
  on_audio_room: ^2.2.1+1
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  provider: ^6.0.5
  search_page: ^2.3.0
  shared_preferences: ^2.1.0
  marquee: ^2.2.3
  scrollable_positioned_list: ^0.3.6
  oktoast: ^3.3.1
  photo_manager: ^2.6.0
  device_display_brightness: ^0.0.6
  flick_video_player: ^0.5.0
  visibility_detector: ^0.4.0+2
  video_player: ^2.6.1
  image_picker: ^0.8.7+4
  font_awesome_flutter: ^10.4.0
  scroll_snap_list: ^0.9.1
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  share_plus: ^6.3.4
  byte_converter: ^1.3.0
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.7.0
  flutter_adaptive_ui: ^0.8.0+1
#  on_audio_edit: ^1.5.1
  intl: ^0.18.1
  photo_view: ^0.14.0
  text_editor: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get:
  group_radio_button: ^1.3.0
  collection: ^1.17.0
  photo_gallery: ^1.1.1
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.1



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: BaiJamjuree-Bold
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-Bold.ttf
    - family: BaiJamjuree-BoldItalic
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-BoldItalic.ttf
    - family: BaiJamjuree-ExtraLight
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-ExtraLight.ttf
    - family: BaiJamjuree-ExtraLightItalic
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-ExtraLightItalic.ttf
    - family: BaiJamjuree-Italic
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-Italic.ttf
    - family: BaiJamjuree-Light
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-Light.ttf
    - family: BaiJamjuree-LightItalic
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-LightItalic.ttf
    - family: BaiJamjuree-Medium
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-Medium.ttf
    - family: BaiJamjuree-MediumItalic
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-MediumItalic.ttf
    - family: BaiJamjuree-Regular
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-Regular.ttf
    - family: BaiJamjuree-SemiBold
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-SemiBold.ttf
    - family: BaiJamjuree-SemiBoldItalic
      fonts:
        - asset: assets/fonts/Bai_Jamjuree/BaiJamjuree-SemiBoldItalic.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
